In [82]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('./data/tmdb_5000_movies.csv')
credits = pd.read_csv('./data/tmdb_5000_credits.csv')
print(movies.shape)
movies.head(5)

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [83]:
from ast import literal_eval

movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]
movies_df.head(5)

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3        9106  112.312950  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4        2124   43.926995  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [84]:
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])



In [85]:
movies_df[['genres', 'keywords']][:1]
##movies_df['genres'].head(3)

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...

In [87]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
count_vec = CountVectorizer(min_df=0, ngram_range=(1, 2))
genre_mat = count_vec.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [88]:

genre_similarity = cosine_similarity(genre_mat, genre_mat)
print(genre_similarity.shape)
print(genre_similarity[:1])

genre_similarity_sorted = genre_similarity.argsort()[:, ::-1]
print(genre_similarity_sorted[:1])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]]
[[   0 3494  813 ... 3038 3037 2401]]


for record 0, 3494th record has the highest similarity except for 0 followed by the next records.
>> use such index to extract specific records and those with high cosine similarity

## Genre-based content filtering

In [89]:
def find_sim_movies(df, sorted_index, title_name, top_n = 10):
    title_moive = df[df['title']== title_name]
    
    title_index = title_moive.index.values
    sim_indexes = sorted_index[title_index, :(top_n)]
    
    print(sim_indexes)
    sim_indexes = sim_indexes.reshape(-1)
    
    return df.iloc[sim_indexes]

In [105]:
(movies_df['title'].head(5))

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: title, dtype: object

In [91]:
movie_title_name = 'Avatar'
similar_movies = find_sim_movies(movies_df, genre_similarity_sorted, movie_title_name, 10)
similar_movies[['title', 'vote_average']]

[[   0 3494  813  870   46   14 1296 1652  419  420]]


title  vote_average
0                                        Avatar           7.2
3494  Beastmaster 2: Through the Portal of Time           4.6
813                                    Superman           6.9
870                                 Superman II           6.5
46                   X-Men: Days of Future Past           7.5
14                                 Man of Steel           6.5
1296                               Superman III           5.3
1652                       Dragonball Evolution           2.9
419                                      Jumper           5.9
420                 Hellboy II: The Golden Army           6.5

In [92]:
movie_title_name = 'The Godfather'
similar_movies = find_sim_movies(movies_df, genre_similarity_sorted, movie_title_name, 10)
similar_movies[['title', 'vote_average']]

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [93]:
##to check if the vote_average is biased, use sort_values

test_df = movies_df[movies_df['vote_count'] >= 1]
test_df[['title', 'vote_average', 'vote_count']].sort_values('vote_count', ascending = True)[:20]

title  vote_average  \
2272                                            Dwegons           0.5   
4764                          Dawn of the Crescent Moon           2.0   
4763                        Smiling Fish & Goat On Fire           7.0   
4027                      Valley of the Heart's Delight           7.0   
4561           Born to Fly: Elizabeth Streb vs. Gravity           5.0   
4562                           The Little Ponderosa Zoo           2.0   
4241                                          The Salon           3.5   
4571  Rise of the Entrepreneur: The Search for a Bet...           8.0   
4757                                      Bending Steel           5.0   
4581                               Gory Gory Hallelujah           1.0   
4702                                     Perfect Cowboy           5.0   
4754                                      The Naked Ape           5.0   
4560                                         Rodeo Girl           5.5   
4045                              Dancer, Texas Pop. 81          10.0   
4644                                    Teeth and Blood           3.0   
4405                                  Karachi se Lahore           8.0   
3129                                     Jungle Shuffle           6.5   
4124                                 This Thing of Ours           5.0   
4403                                     The Jimmy Show           8.0   
4252                                       Last I Heard           6.0   

      vote_count  
2272           1  
4764           1  
4763           1  
4027           1  
4561           1  
4562           1  
4241           1  
4571           1  
4757           1  
4581           1  
4702           1  
4754           1  
4560           1  
4045           1  
4644           1  
4405           1  
3129           1  
4124           1  
4403           1  
4252           1

In [94]:
movies_df[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending = False)[:20]

title  vote_average  vote_count
3519                 Stiff Upper Lips          10.0           1
4247            Me You and Five Bucks          10.0           2
4045            Dancer, Texas Pop. 81          10.0           1
4662                   Little Big Top          10.0           1
3992                        Sardaarji           9.5           2
2386                   One Man's Hero           9.3           2
2970               There Goes My Baby           8.5           2
1881         The Shawshank Redemption           8.5        8205
2796            The Prisoner of Zenda           8.4          11
3337                    The Godfather           8.4        5893
2294                    Spirited Away           8.3        3840
3865                         Whiplash           8.3        4254
2731           The Godfather: Part II           8.3        3338
3232                     Pulp Fiction           8.3        8428
662                        Fight Club           8.3        9413
4755                         Counting           8.3           3
1818                 Schindler's List           8.3        4329
1990          The Empire Strikes Back           8.2        5879
65                    The Dark Knight           8.2       12002
3719  One Flew Over the Cuckoo's Nest           8.2        2919

## weighted rating used by IMDB

WR = (v/(v+m))*r + (m/(v+m))*c

r = mean voting rate for individual movies

v = number of votes for individual movies

m = minimum votes required to be listed in the Top Rated List

c = mean vote acrosee the whole report (all movies)


referred from "https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV#"


In [95]:
c = movies_df['vote_average'].mean()

# set as the top 70% count - because I love number 7
percentile = 0.7
m = movies_df['vote_count'].quantile(percentile)

print("c: ", c)
print("m: ", m)

c:  6.092171559442011
m:  581.0


In [103]:
c = movies['vote_average'].mean()

percentile = 0.7
m = movies['vote_count'].quantile(percentile)

def weighted_rating(input_data):
    r = input_data['vote_average']
    v = input_data['vote_count']
    
    weighted_rating_result = (v/(v+m))*r + (m/(v+m))*c
    
    return weighted_rating_result

movies['weighted_vote'] = movies.apply(weighted_rating, axis=1)

movies_df['weighted_vote'] = movies_df.apply(weighted_rating, axis=1)
movies_df[['title', 'genres', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', ascending=False).head(15)

title  \
1881                       The Shawshank Redemption   
3337                                  The Godfather   
662                                      Fight Club   
3232                                   Pulp Fiction   
65                                  The Dark Knight   
809                                    Forrest Gump   
1818                               Schindler's List   
3865                                       Whiplash   
96                                        Inception   
1990                        The Empire Strikes Back   
2294                                  Spirited Away   
95                                     Interstellar   
2731                         The Godfather: Part II   
329   The Lord of the Rings: The Return of the King   
2912                                      Star Wars   

                                                 genres  vote_average  \
1881                                     [Drama, Crime]           8.5   
3337                                     [Drama, Crime]           8.4   
662                                             [Drama]           8.3   
3232                                  [Thriller, Crime]           8.3   
65                     [Drama, Action, Crime, Thriller]           8.2   
809                            [Comedy, Drama, Romance]           8.2   
1818                              [Drama, History, War]           8.3   
3865                                            [Drama]           8.3   
96    [Action, Thriller, Science Fiction, Mystery, A...           8.1   
1990               [Adventure, Action, Science Fiction]           8.2   
2294            [Fantasy, Adventure, Animation, Family]           8.3   
95                  [Adventure, Drama, Science Fiction]           8.1   
2731                                     [Drama, Crime]           8.3   
329                        [Adventure, Fantasy, Action]           8.1   
2912               [Adventure, Action, Science Fiction]           8.1   

      weighted_vote  vote_count  
1881       8.340775        8205  
3337       8.192887        5893  
662        8.171648        9413  
3232       8.157615        8428  
65         8.102674       12002  
809        8.056059        7927  
1818       8.038748        4329  
3865       8.034695        4254  
96         8.018611       13752  
1990       8.010426        5879  
2294       8.009851        3840  
95         7.998100       10867  
2731       7.972685        3338  
329        7.965061        8064  
2912       7.938092        6624

In [106]:
def find_sim_movies_wr(df, sorted_index, title_name, top_n = 10):
    title_moive = df[df['title']== title_name]
    
    title_index = title_moive.index.values
    sim_indexes = sorted_index[title_index, :(top_n)]
    
    print(sim_indexes)
    sim_indexes = sim_indexes.reshape(-1)
    
    return df.iloc[sim_indexes].sort_values('weighted_vote', ascending=False).head(top_n)




In [182]:
from random import randint

value = randint(0, len(movies_df))
#print(value)
rand_title = movies_df.loc[value]['title']

final_recommend = find_sim_movies_wr(movies_df, genre_similarity_sorted, rand_title, 10)

print('\033[1m' + "Looking for movies similar to this?: ", rand_title)
final_recommend[['id','title', 'genres', 'vote_average', 'weighted_vote', 'vote_count']].head(5)

[[2195 1850 3316 2218 2435 3073 1503 1470 4230  629]]
Looking for movies similar to this?:  Stolen


id           title                            genres  vote_average  \
1850     111        Scarface  [Action, Crime, Drama, Thriller]           8.0   
2435    7304  Running Scared  [Action, Crime, Drama, Thriller]           7.0   
3316   11022            Narc  [Action, Crime, Drama, Thriller]           6.8   
2218   11835  Death Sentence  [Action, Crime, Drama, Thriller]           6.5   
629   136797  Need for Speed  [Action, Crime, Drama, Thriller]           6.1   

      weighted_vote  vote_count  
1850       7.685903        2948  
2435       6.421658         331  
3316       6.231192         142  
2218       6.230127         297  
629        6.097835        1520